<?php

namespace Integration\Weather;

use Carbon\Carbon;

class WeatherIntegrationTest extends \TestCase
{
    protected function setUp(): void
    {
        Carbon::setTestNow(Carbon::create(2018, 1, 2));

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function requestFahrenheitReturnsFahrenheitUnits()
    {
        $this->get('/weather?city=AMS&date=12/01/2018&unit=F');

        $this->seeJson([
            'temperature' => 26,
            'unit' => 'F',
            'city' => 'Amsterdam',
            'date' => '12/01/2018'
        ]);
    }

    /** @test */
    public function requestCelsiusReturnsCelsiusUnits()
    {
        $this->get('/weather?city=AMS&date=12/01/2018&unit=C');

        $this->seeJson([
            'temperature' => -3,
            'unit' => 'C',
            'city' => 'Amsterdam',
            'date' => '12/01/2018'
        ]);
    }

    /** @test */
    public function requestForDatesInThePastReturnsInvalidDateResponse()
    {
        $this->get('/weather?city=AMS&date=01/01/2018&unit=C');

        $this->seeJson([
            'message' => 'Invalid date requested',
            'date' => '01/01/2018'
        ]);
    }

    /** @test */
    public function requestForDatesMoreThan10DaysIntoTheFutureReturnsInvalidDateResponse()
    {
        $this->get('/weather?city=AMS&date=13/01/2018&unit=C');

        $this->seeJson([
            'message' => 'Invalid date requested',
            'date' => '13/01/2018'
        ]);
    }
}
